---
#
# Make sure that vagrant is up and create the inventory
#

- name: Create machines and build dynamic inventory
  hosts: localhost
  become: no 
  roles:
    - create_inventory


- name: Wait until all machines are up
  hosts: all
  become: yes
  tasks:
    - name: Ping machines
      ping:

- name: Install ZooKeeper
  hosts: zookeeper_nodes
  become: yes
  roles:
    - zookeeper