---
- name: Download archive 
  get_url:
    url: "{{kafka_download_url}}"
    checksum: "{{kafka_md5_sum}}"
    dest: "/home/vagrant/kafka_2.13-2.4.1.tgz"

- name: Make sure that /opt/kafka exists 
  file:
    path: "/opt/kafka"
    state: directory

- name: Extract archive 
  unarchive:
    remote_src: yes 
    dest: /opt/kafka
    src: "/home/vagrant/kafka_2.13-2.4.1.tgz"

- name: Update configuration 
  template:
    src: server.properties.j2
    dest: /opt/kafka/kafka_2.13-2.4.1/config/server.properties
    mode: 0644
    owner: root 
    group: root

- name: Create directory to hold PKI data
  file:
    path: "/opt/kafka/kafka_2.13-2.4.1/pki"
    state: directory

- name: Copy server keystore 
  copy:
    src: "{{playbook_dir}}/.state/certs/broker{{broker_id}}.p12"
    dest: "/opt/kafka/kafka_2.13-2.4.1/pki/server.keystore.p12"

- name: Create systemd unit file
  template:
    src: kafka.service.j2
    dest: /lib/systemd/system/kafka.service
    mode: 0644
    owner: root 
    group: root
  
- name: Start Kafka 
  service:
    daemon_reload: yes 
    name: kafka 
    state: restarted 