- name: Start networks
  virt_net:
    name: "{{item}}"
    state: active
  loop:
  - kafka-private

- name: Run Vagrant 
  shell: |
    vagrant up

- name: Get public IP addresses 
  shell: |
    virsh domifaddr kafka_broker{{item}} | grep "ipv4" | awk '{ print $4 }' | sed 's/\/24//'
  loop: "{{ range(1, 4) | list }}"
  register: 
    ip_addresses 

- name: Build dynamic inventory 
  add_host:
    name: "broker{{item.item}}"
    groups: ["brokers","zookeeper_nodes"]
    ansible_ssh_host: "{{item.stdout}}"
    ansible_ssh_user: "vagrant"
    ansible_ssh_private_key_file: "{{playbook_dir}}/.vagrant/machines/broker{{item.item}}/libvirt/private_key"
    mgmt_ip: "10.100.0.1{{item.item}}"
    broker_id: "{{item.item}}"
    zookeeper_id: "{{item.item}}"
    private_hostname: "broker{{item.item}}"
  loop: "{{ip_addresses.results}}"
  loop_control:
    label: "broker{{item.item}}"

- name: Make sure that state directory exists 
  file:
    path: "{{playbook_dir}}/.state"
    state: directory

- name: Create file with broker configuration 
  template:
    src: config.yaml.j2
    dest: "{{playbook_dir}}/.state/config.yaml"